binary_sensor:

  - id: zone9
    name: Zone 9    
    pin:
      number: $zone9
      mode: INPUT
    platform: gpio   
    device_class: $zone9_device_class
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
