binary_sensor:

  - id: zone8
    name: Zone 8    
    pin:
      number: $zone8
      mode: INPUT_PULLUP
    platform: gpio   
    device_class: $zone8_device_class
    filters:
      - delayed_on_off: $sensor_debounce_time
    on_state:
      then:
        - light.turn_on: blue_status_led
        - delay: 100ms
        - light.turn_off: blue_status_led
